[package]
name = "rstest-insta-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.3"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
insta = "1.43"
prettyplease = "0.2"
rstest = "0.25"
